<?xml version="1.0" encoding="utf-8"?>
<DataListDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DataList.xsd" Version="1.2">
  <DataList Id="bc259013-4d9f-4a16-97a5-c652fdad356b" ConfigurationUri="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/efa4d6fe-6800-4466-b9d3-9d3a161abbc2" PlcIdentifier="d79c6d15-0a0b-4666-b314-2801556c3136" TargetAttributes="PlcNext,UserManagedComponentInstances,ResourceGlobalPorts" TargetVersion="0/2023.0.0" UICulture="en-US">
    <Datum Uuid="3c32aa81-cdde-41cf-a964-65345f8ffc04">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="537192d2-3605-4ea2-9973-9ac6210e470c" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment>Higher level PLC in RUN</Comment>
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PND_S1_PLC_RUN</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pndpd1]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>PND_S1_PLC_RUN</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="69a41c0b-85a3-48a2-8a2c-878940a7d8db">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c348e117-a229-4f90-b7df-5fddb6ba2c71" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment>Connection to Profinet-Controller</Comment>
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PND_S1_VALID_DATA_CYCLE</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pndpd2]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>PND_S1_VALID_DATA_CYCLE</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ae4f0a0b-73a2-47ab-8275-619674e29b8d">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="aeb92a4e-e2c4-49a7-9a16-a477ef72bc13" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment>IOP status of the higher-level control system</Comment>
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PND_S1_OUTPUT_STATUS_GOOD</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pndpd3]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>PND_S1_OUTPUT_STATUS_GOOD</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4def25e7-2a78-471a-9997-dda84ac23800">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6a73ff14-0947-4dc6-8c78-4a0de2794964" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment>IOC status of the higher-level control system</Comment>
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PND_S1_INPUT_STATUS_GOOD</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pndpd4]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>PND_S1_INPUT_STATUS_GOOD</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c5d0c218-63fa-4697-9757-f1137eac6e18">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="9f56019c-b813-4922-9b30-8fec2e9b8b12" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment>Process data length</Comment>
        <DataType>WORD</DataType>
        <InitValue>WORD#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PND_S1_DATA_LENGTH</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=pndpd5]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>Bitstring16</DataType>
        <IsSafe>False</IsSafe>
        <Label>PND_S1_DATA_LENGTH</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ea03425f-fb95-4ef0-882f-5efdb5333be6">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="3d71ac46-5755-4de0-b6ba-424365e3740f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment>Output process data</Comment>
        <DataType>PND_IO_512</DataType>
        <InitValue />
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PND_S1_OUTPUTS</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=pndpd6]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Write</Access>
        <DataType>Octetstring[512]</DataType>
        <IsSafe>False</IsSafe>
        <Label>PND_S1_OUTPUTS</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="8e5381ca-acdd-4f4a-8897-1f386517a0bf">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="eb6f4a81-56c6-4556-b8d7-581502a2319e" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment>Input process data</Comment>
        <DataType>PND_IO_512</DataType>
        <InitValue />
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PND_S1_INPUTS</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=pndpd7]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>Octetstring[512]</DataType>
        <IsSafe>False</IsSafe>
        <Label>PND_S1_INPUTS</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ef244b9b-a815-46be-a3e8-27ab99680a8f">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="d34b2fb5-47aa-4223-8ffa-4f0b42b0ef65" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>INT</DataType>
        <InitValue>INT#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PND_IO_DRIVEN_BY_PLC</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=pndpd8]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>Signed16</DataType>
        <IsSafe>False</IsSafe>
        <Label>PND_IO_DRIVEN_BY_PLC</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="59ab1a8f-27c2-412c-be09-23966409eda4">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="109c87f5-15c4-46fa-9927-83b3bdc19fa8" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BYTE</DataType>
        <InitValue>BYTE#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>AXIO_DIAG_STATUS_REG_HI</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=axiod0]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_ax">
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Label>AXIO_DIAG_STATUS_REG_HI</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="57f02a64-356c-4217-95bb-a7bc34a9bce4">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="4970bfae-1a9e-42c5-ac01-79b73b5b34ee" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BYTE</DataType>
        <InitValue>BYTE#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>AXIO_DIAG_STATUS_REG_LOW</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=axiod1]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_ax">
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Label>AXIO_DIAG_STATUS_REG_LOW</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="3fe1a094-f8f3-4a84-8fa0-89ee08115fad">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f9c742d2-ae01-4335-a884-d5f59b84968a" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BYTE</DataType>
        <InitValue>BYTE#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>AXIO_DIAG_PARAM_REG_HI</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=axiod2]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_ax">
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Label>AXIO_DIAG_PARAM_REG_HI</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="3582e6e9-5cce-4827-b5e4-fb955fd8904e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="91b09ded-384d-4cbe-8d90-6fa0f6210adc" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BYTE</DataType>
        <InitValue>BYTE#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>AXIO_DIAG_PARAM_REG_LOW</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=axiod3]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_ax">
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Label>AXIO_DIAG_PARAM_REG_LOW</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="405b2dfc-41b0-4beb-bcf7-93732ef7b306">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="d50dbe9b-8f5b-4ee2-9fde-02edc5c47492" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BYTE</DataType>
        <InitValue>BYTE#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>AXIO_DIAG_PARAM_2_REG_HI</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=axiod4]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_ax">
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Label>AXIO_DIAG_PARAM_2_REG_HI</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7535ddff-50b3-4f9a-9d0b-272ba1121e34">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c0572910-d732-4cbf-934d-a59332a3e3ce" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BYTE</DataType>
        <InitValue>BYTE#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>AXIO_DIAG_PARAM_2_REG_LOW</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=axiod5]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_ax">
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Label>AXIO_DIAG_PARAM_2_REG_LOW</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="b7f7be7a-244e-47bb-ac54-6a81775f8907">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="70c14de1-bbcc-4f88-a979-4768b658acba" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>AXIO_DIAG_STATUS_REG_PF</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=axiod6]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_ax">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>AXIO_DIAG_STATUS_REG_PF</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="264fcee8-10b3-4272-96c6-0f72a6f3bede">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="9f42d7c2-bd5d-4129-a2be-c24eabbe6c17" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>AXIO_DIAG_STATUS_REG_BUS</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=axiod7]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_ax">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>AXIO_DIAG_STATUS_REG_BUS</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="3cdca42b-a401-4bf0-9fc4-c8cf7a96676b">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="bcfa959b-0906-4620-9dbc-8e0b296a6e25" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>AXIO_DIAG_STATUS_REG_RUN</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=axiod8]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_ax">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>AXIO_DIAG_STATUS_REG_RUN</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="6b74eaaf-be87-4855-9959-3dd91d1f3515">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c4926b18-1492-4b33-aba7-b2db6135f732" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>AXIO_DIAG_STATUS_REG_ACT</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=axiod9]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_ax">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>AXIO_DIAG_STATUS_REG_ACT</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="856b3c07-12ec-4465-a364-f1fe295704a1">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="354f6527-6306-4925-8397-30873947820c" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>AXIO_DIAG_STATUS_REG_RDY</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=axiod10]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_ax">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>AXIO_DIAG_STATUS_REG_RDY</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="421efe74-c57c-49a5-aec2-af3d456709d0">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="57d59444-7eb1-4f71-ab4a-d74b20e921cc" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>AXIO_DIAG_STATUS_REG_SYSFAIL</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=axiod11]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_ax">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>AXIO_DIAG_STATUS_REG_SYSFAIL</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="fff93e2a-82df-49d0-bf95-4eb7e736d3c4">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="424f7a6c-65d9-43eb-aee0-86147de7378f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>AXIO_DIAG_STATUS_REG_PW</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=axiod12]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_ax">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>AXIO_DIAG_STATUS_REG_PW</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="1abfe123-bbe8-464a-8226-6a9cdfecc6b2">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="74957ba8-75e9-4271-80fc-f26acb6bca36" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BYTE</DataType>
        <InitValue>BYTE#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_STATUS_REG_HI</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pdib1]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_STATUS_REG_HI</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="8ec355a8-6c9e-44e1-a3ed-5b5ca8a443d6">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="47c17b9c-d5bf-4d26-b143-7b999ee607c6" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BYTE</DataType>
        <InitValue>BYTE#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_STATUS_REG_LOW</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pdib2]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_STATUS_REG_LOW</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="9c048fcf-18f7-458f-9bc3-3730dba45711">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1fea2f21-d918-441d-9a83-19105bee9cee" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_STATUS_REG_SYSFAIL</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pdib3]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_STATUS_REG_SYSFAIL</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="dddfbc55-1cb3-420b-ab8e-ff23e030b41a">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c551c0a6-deac-4718-87dc-d6c2fda26d8c" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_STATUS_REG_WARN</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pdib4]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_STATUS_REG_WARN</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c9872ef0-dc48-4701-8e62-2b314acd62e5">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="d620acb6-5528-45c5-99d6-ee8cb57c0f72" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_STATUS_REG_QUAL</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=pdib5]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_STATUS_REG_QUAL</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="11a544e6-17d4-49e9-9685-011138beb240">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c9c3142c-4874-4c28-a755-6591774541a6" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_STATUS_REG_USER</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=pdib6]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_STATUS_REG_USER</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="70e408b1-5584-481c-9df0-6eef9b06f1c2">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="491eabf8-b483-4726-bd90-62f42392b201" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_STATUS_REG_PF</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=pdib7]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_STATUS_REG_PF</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="28aba217-96ac-42b5-93fe-bf896d04d8e0">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f2c439be-7073-42d6-90ec-4c043528e1c6" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_STATUS_REG_BUS</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=pdib8]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_STATUS_REG_BUS</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="36625ac7-adfa-4985-ad60-1d3bc441a289">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="0edd9fcb-ddb8-4db1-9ab3-524d7f98ebbd" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_STATUS_REG_CTRL</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=pdib9]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_STATUS_REG_CTRL</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="2d804d60-c3d4-4f45-9464-34a4674a5cd5">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="b2109ab2-b814-4302-9159-40eb16dc02a6" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_STATUS_REG_DTC</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=pdib10]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_STATUS_REG_DTC</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="34dacb0d-7bd2-48a1-b3fc-8fb4731ed0a7">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="738d51ce-7b9d-4c4a-aa49-8e29e398c78b" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_STATUS_REG_RUN</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=pdib11]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_STATUS_REG_RUN</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="a2f5a596-3aac-4a2c-9947-15449a17efba">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a4e09de0-4959-496d-a60d-52404a52f9a3" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_STATUS_REG_ACT</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=pdib12]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_STATUS_REG_ACT</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4257ab4d-615c-4138-810e-a6f2d2b6b144">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a1afe0d1-8ff2-4972-a193-8c2194c1deec" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_STATUS_REG_RDY</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=pdib13]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_STATUS_REG_RDY</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c7c3fbd9-2e13-4b08-be9d-7e8b3dfab61b">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="7bb2496a-f64e-4bda-9880-81fd1a6ede7b" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BYTE</DataType>
        <InitValue>BYTE#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_PARAM_REG_HI</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=pdib14]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_PARAM_REG_HI</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="bb116033-6b69-4110-b1cd-c1342097e53e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="75bc764b-57ab-4d1f-a6b8-51145f39dea5" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BYTE</DataType>
        <InitValue>BYTE#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_PARAM_REG_LOW</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=pdib15]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_PARAM_REG_LOW</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="1119ecc9-4c5d-45d3-b17e-26e38d0fd2ff">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="bf5e3604-46dc-4a24-badf-420d96925ed2" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BYTE</DataType>
        <InitValue>BYTE#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_PARAM_2_REG_HI</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=pdib16]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_PARAM_2_REG_HI</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7fc0fa3e-dd37-40f3-9b9a-93289c467a98">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f14d4c52-a128-437b-8cfa-1e481fd11b83" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BYTE</DataType>
        <InitValue>BYTE#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IB_DIAG_PARAM_2_REG_LOW</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=pdib17]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_8">
        <Access>Read</Access>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Label>IB_DIAG_PARAM_2_REG_LOW</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="6dc9740c-fd26-41c0-bbdc-510c8c4fd8fa">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="481ab28e-6429-4ef5-8f9d-fc2b5a2dd877" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>ESM_DAT</DataType>
        <InitValue />
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>ESM_DATA</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pdesm1]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_1">
        <Access>Read</Access>
        <DataType>ESM_DAT</DataType>
        <IsSafe>False</IsSafe>
        <Label>ESM_DATA</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="b7d6e3e6-7733-4c2b-a8da-0d724d6d35ba">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="14a3e15e-1b48-44ae-96bb-fe4de07fe0e9" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>RTC_TYPE</DataType>
        <InitValue />
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>RTC</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pddi1]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_1">
        <Access>Read</Access>
        <DataType>RTC_TYPE</DataType>
        <IsSafe>False</IsSafe>
        <Label>RTC</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="17167699-e4af-40b1-8431-5fcfa19024a2">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="d35694e2-8323-481b-9a01-c03c7523a3d9" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>DEVICE_STATE_2152_TYPE</DataType>
        <InitValue />
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>DEVICE_STATE</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pddi2]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_1">
        <Access>Read</Access>
        <DataType>DEVICE_STATE_2152_TYPE</DataType>
        <IsSafe>False</IsSafe>
        <Label>DEVICE_STATE</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="500644a5-f6fe-46f9-a9b5-03630af1c55d">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="aaa00231-35cc-4325-9210-dc81e2aba637" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>PARTITION_INFO</DataType>
        <InitValue />
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>USER_PARTITION</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pddi4]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_1">
        <Access>Read</Access>
        <DataType>PARTITION_INFO</DataType>
        <IsSafe>False</IsSafe>
        <Label>USER_PARTITION</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="175231ba-2acc-4c46-a60c-15f20328f170">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="4be5a188-f17b-4f23-aef1-89a0bed62eb4" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PNIO_SYSTEM_BF</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=pncpd1]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>PNIO_SYSTEM_BF</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="e8582023-2023-45b5-be57-9438828ba3ca">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="38b238c1-7294-473a-b1f8-03ec206dc994" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PNIO_SYSTEM_SF</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=pncpd2]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>PNIO_SYSTEM_SF</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ee1532b9-1701-45ee-a1e4-ad2abecb4a25">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ab2c4c01-a832-47c1-915c-05a523de28df" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PNIO_MAINTENANCE_DEMANDED</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=pncpd3]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>PNIO_MAINTENANCE_DEMANDED</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="6d893551-4b63-4c65-82a7-86c28eb6a1c5">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="b7d0c724-fd09-47d6-a7c7-b706d0c76e9e" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PNIO_MAINTENANCE_REQUIRED</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=pncpd4]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>PNIO_MAINTENANCE_REQUIRED</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="b608b5b7-da50-4343-a405-c04dd572d4cd">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="65078bdf-a185-4ccf-a086-6f4872d0dcb3" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>WORD</DataType>
        <InitValue>WORD#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PNIO_CONFIG_STATUS</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=pncpd5]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>Bitstring16</DataType>
        <IsSafe>False</IsSafe>
        <Label>PNIO_CONFIG_STATUS</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="54a6b89a-2502-439e-b6ca-a9ce0db69afa">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="47c66a05-f582-4381-94a0-53da53f901d7" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PNIO_CONFIG_STATUS_ACTIVE</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=pncpd6]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>PNIO_CONFIG_STATUS_ACTIVE</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="98d31470-2250-4870-ad75-5234a77aeb64">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="25b259fe-0758-4a16-8234-f107786382cb" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PNIO_CONFIG_STATUS_READY</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=pncpd7]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>PNIO_CONFIG_STATUS_READY</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="9e430274-59ea-42e3-9208-85d7ca3a29b4">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="108b16f1-ebce-4011-aabe-374b231d74ef" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PNIO_CONFIG_STATUS_CFG_FAULT</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=pncpd8]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Read</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>PNIO_CONFIG_STATUS_CFG_FAULT</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="b3faba97-a234-4156-b85a-3009f167086e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="54130068-429f-4747-a66c-21838762640f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PNIO_FORCE_FAILSAFE</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=pncpd9]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_4">
        <Access>Write</Access>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Label>PNIO_FORCE_FAILSAFE</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="be2b7911-a465-4a4e-95e4-f9258fc7888d">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="966b360a-027b-4bdd-b951-14e9290cb4ea" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address>%MW1.30000</Address>
        <Comment />
        <DataType>UINT</DataType>
        <InitValue>UINT#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>IP_ACTIVE_SOCKETS</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="1b22babd-016f-4030-aeff-c5fc76ca79ea">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="44676708-ba3c-465a-a80d-4c432f8259d1" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address>%MW1.30100</Address>
        <Comment />
        <DataType>UINT</DataType>
        <InitValue>UINT#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>TLS_ACTIVE_SOCKETS</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="f9cf8fd3-c720-46e3-8c9c-05db58ff896a">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="07bd8833-9a84-4f73-b871-7ae0db3b9440" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>HMI_STATUS_TYPE2</DataType>
        <InitValue />
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>HMI_STATUS2</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=hmipd001]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_3">
        <Access>Read</Access>
        <DataType>HMI_STATUS_TYPE2</DataType>
        <IsSafe>False</IsSafe>
        <Label>HMI_STATUS2</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="07b6efc3-0e34-4b1c-8026-5d718c79e76e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="cefec7bd-a6d2-451e-abdb-e1163b0b38d2" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>HMI_CONTROL_TYPE</DataType>
        <InitValue />
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>HMI_CONTROL</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=hmipd002]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_3">
        <Access>Write</Access>
        <DataType>HMI_CONTROL_TYPE</DataType>
        <IsSafe>False</IsSafe>
        <Label>HMI_CONTROL</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="807c1273-71a0-4ebb-9af3-16de36b7ec5a">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="fa0e2a3b-5fbe-4b86-9560-072778840f3c" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>EIPD_IO_ARRAY</DataType>
        <InitValue />
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>EIPD_INPUTS</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=eip001]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_7">
        <Access>Read</Access>
        <DataType>EIPD_IO_ARRAY</DataType>
        <IsSafe>False</IsSafe>
        <Label>EIPD_INPUTS</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="9fed9090-38fd-4992-852e-f6112b0d490e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="8011a1db-e944-48ac-99e3-fab60353d1c8" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>EIPD_IO_ARRAY</DataType>
        <InitValue />
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>EIPD_OUTPUTS</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=eip002]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_7">
        <Access>Write</Access>
        <DataType>EIPD_IO_ARRAY</DataType>
        <IsSafe>False</IsSafe>
        <Label>EIPD_OUTPUTS</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7d18cd7c-11be-41b1-aa4c-51fee4e25417">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="34747357-2dcc-4256-b6f8-690be6fa2e71" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>EIPD_VALID_DATA_CYCLE</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=eip003]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_7">
        <Access>Read</Access>
        <DataType>Boolean</DataType>
        <IsSafe>False</IsSafe>
        <Label>EIPD_VALID_DATA_CYCLE</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="cfbf5f95-a843-421b-9c8b-5032d448b5f6">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="3f2f1237-c93d-4fd3-882d-06b527b43b46" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>EIPD_PEER_IDLE</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=eip004]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_7">
        <Access>Read</Access>
        <DataType>Boolean</DataType>
        <IsSafe>False</IsSafe>
        <Label>EIPD_PEER_IDLE</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="39e6d770-f5af-4396-ac8e-9e7ea174e8b0">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="e36016ac-e690-42e8-94a0-c03a648a9324" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>BOOL</DataType>
        <InitValue>FALSE</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>EIPD_PEER_RUN</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=eip005]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_7">
        <Access>Read</Access>
        <DataType>Boolean</DataType>
        <IsSafe>False</IsSafe>
        <Label>EIPD_PEER_RUN</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="b4355e44-dc99-4876-9eb6-e1b274d0a85b">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="09a0b2de-a835-4ff4-bc6d-fa84dc742a56" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>WORD</DataType>
        <InitValue>WORD#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>EIPD_OUTPUTS_LENGTH</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=eip006]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_7">
        <Access>Read</Access>
        <DataType>Bitstring16</DataType>
        <IsSafe>False</IsSafe>
        <Label>EIPD_OUTPUTS_LENGTH</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="610947b2-1eb9-4aa4-a147-1c8eefd2459e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="025c9fc2-446c-4593-a8c8-79422586b017" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address />
        <Comment />
        <DataType>WORD</DataType>
        <InitValue>WORD#16#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>EIPD_INPUTS_LENGTH</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=eip007]" SourceId="d79c6d15-0a0b-4666-b314-2801556c3136.L7_7">
        <Access>Read</Access>
        <DataType>Bitstring16</DataType>
        <IsSafe>False</IsSafe>
        <Label>EIPD_INPUTS_LENGTH</Label>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ab9ff9bf-3da9-4800-a790-98b2c62c033c">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="78c85abe-1ce2-45a6-a727-03f56cd3933f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a">
        <Address>%ML1.10000</Address>
        <Comment />
        <DataType>ULINT</DataType>
        <InitValue>ULINT#0</InitValue>
        <IsConstant>False</IsConstant>
        <IsHmi>False</IsHmi>
        <IsOpc>False</IsOpc>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <IsRetain>False</IsRetain>
        <Name>PLC_CRC_PRJ</Name>
        <Usage>Global</Usage>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <RoleGroupList RoleTypeName="Variable">
      <RoleGroup SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a" ObjectId="fb84caa8-36a3-47d9-8bf0-95ff0e8a7b24" DisplayName="Default" IsReadOnly="False" />
      <RoleGroup SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e303fb44-96a7-4a68-be3d-e719000abe7a" ObjectId="971398c9-e054-4349-a1d9-e00a1840c9f4" DisplayName="System Variables" IsReadOnly="True">
        <RoleDatumUuid>3c32aa81-cdde-41cf-a964-65345f8ffc04</RoleDatumUuid>
        <RoleDatumUuid>69a41c0b-85a3-48a2-8a2c-878940a7d8db</RoleDatumUuid>
        <RoleDatumUuid>ae4f0a0b-73a2-47ab-8275-619674e29b8d</RoleDatumUuid>
        <RoleDatumUuid>4def25e7-2a78-471a-9997-dda84ac23800</RoleDatumUuid>
        <RoleDatumUuid>c5d0c218-63fa-4697-9757-f1137eac6e18</RoleDatumUuid>
        <RoleDatumUuid>ea03425f-fb95-4ef0-882f-5efdb5333be6</RoleDatumUuid>
        <RoleDatumUuid>8e5381ca-acdd-4f4a-8897-1f386517a0bf</RoleDatumUuid>
        <RoleDatumUuid>ef244b9b-a815-46be-a3e8-27ab99680a8f</RoleDatumUuid>
        <RoleDatumUuid>59ab1a8f-27c2-412c-be09-23966409eda4</RoleDatumUuid>
        <RoleDatumUuid>57f02a64-356c-4217-95bb-a7bc34a9bce4</RoleDatumUuid>
        <RoleDatumUuid>3fe1a094-f8f3-4a84-8fa0-89ee08115fad</RoleDatumUuid>
        <RoleDatumUuid>3582e6e9-5cce-4827-b5e4-fb955fd8904e</RoleDatumUuid>
        <RoleDatumUuid>405b2dfc-41b0-4beb-bcf7-93732ef7b306</RoleDatumUuid>
        <RoleDatumUuid>7535ddff-50b3-4f9a-9d0b-272ba1121e34</RoleDatumUuid>
        <RoleDatumUuid>b7f7be7a-244e-47bb-ac54-6a81775f8907</RoleDatumUuid>
        <RoleDatumUuid>264fcee8-10b3-4272-96c6-0f72a6f3bede</RoleDatumUuid>
        <RoleDatumUuid>3cdca42b-a401-4bf0-9fc4-c8cf7a96676b</RoleDatumUuid>
        <RoleDatumUuid>6b74eaaf-be87-4855-9959-3dd91d1f3515</RoleDatumUuid>
        <RoleDatumUuid>856b3c07-12ec-4465-a364-f1fe295704a1</RoleDatumUuid>
        <RoleDatumUuid>421efe74-c57c-49a5-aec2-af3d456709d0</RoleDatumUuid>
        <RoleDatumUuid>fff93e2a-82df-49d0-bf95-4eb7e736d3c4</RoleDatumUuid>
        <RoleDatumUuid>1abfe123-bbe8-464a-8226-6a9cdfecc6b2</RoleDatumUuid>
        <RoleDatumUuid>8ec355a8-6c9e-44e1-a3ed-5b5ca8a443d6</RoleDatumUuid>
        <RoleDatumUuid>9c048fcf-18f7-458f-9bc3-3730dba45711</RoleDatumUuid>
        <RoleDatumUuid>dddfbc55-1cb3-420b-ab8e-ff23e030b41a</RoleDatumUuid>
        <RoleDatumUuid>c9872ef0-dc48-4701-8e62-2b314acd62e5</RoleDatumUuid>
        <RoleDatumUuid>11a544e6-17d4-49e9-9685-011138beb240</RoleDatumUuid>
        <RoleDatumUuid>70e408b1-5584-481c-9df0-6eef9b06f1c2</RoleDatumUuid>
        <RoleDatumUuid>28aba217-96ac-42b5-93fe-bf896d04d8e0</RoleDatumUuid>
        <RoleDatumUuid>36625ac7-adfa-4985-ad60-1d3bc441a289</RoleDatumUuid>
        <RoleDatumUuid>2d804d60-c3d4-4f45-9464-34a4674a5cd5</RoleDatumUuid>
        <RoleDatumUuid>34dacb0d-7bd2-48a1-b3fc-8fb4731ed0a7</RoleDatumUuid>
        <RoleDatumUuid>a2f5a596-3aac-4a2c-9947-15449a17efba</RoleDatumUuid>
        <RoleDatumUuid>4257ab4d-615c-4138-810e-a6f2d2b6b144</RoleDatumUuid>
        <RoleDatumUuid>c7c3fbd9-2e13-4b08-be9d-7e8b3dfab61b</RoleDatumUuid>
        <RoleDatumUuid>bb116033-6b69-4110-b1cd-c1342097e53e</RoleDatumUuid>
        <RoleDatumUuid>1119ecc9-4c5d-45d3-b17e-26e38d0fd2ff</RoleDatumUuid>
        <RoleDatumUuid>7fc0fa3e-dd37-40f3-9b9a-93289c467a98</RoleDatumUuid>
        <RoleDatumUuid>6dc9740c-fd26-41c0-bbdc-510c8c4fd8fa</RoleDatumUuid>
        <RoleDatumUuid>b7d6e3e6-7733-4c2b-a8da-0d724d6d35ba</RoleDatumUuid>
        <RoleDatumUuid>17167699-e4af-40b1-8431-5fcfa19024a2</RoleDatumUuid>
        <RoleDatumUuid>500644a5-f6fe-46f9-a9b5-03630af1c55d</RoleDatumUuid>
        <RoleDatumUuid>175231ba-2acc-4c46-a60c-15f20328f170</RoleDatumUuid>
        <RoleDatumUuid>e8582023-2023-45b5-be57-9438828ba3ca</RoleDatumUuid>
        <RoleDatumUuid>ee1532b9-1701-45ee-a1e4-ad2abecb4a25</RoleDatumUuid>
        <RoleDatumUuid>6d893551-4b63-4c65-82a7-86c28eb6a1c5</RoleDatumUuid>
        <RoleDatumUuid>b608b5b7-da50-4343-a405-c04dd572d4cd</RoleDatumUuid>
        <RoleDatumUuid>54a6b89a-2502-439e-b6ca-a9ce0db69afa</RoleDatumUuid>
        <RoleDatumUuid>98d31470-2250-4870-ad75-5234a77aeb64</RoleDatumUuid>
        <RoleDatumUuid>9e430274-59ea-42e3-9208-85d7ca3a29b4</RoleDatumUuid>
        <RoleDatumUuid>b3faba97-a234-4156-b85a-3009f167086e</RoleDatumUuid>
        <RoleDatumUuid>be2b7911-a465-4a4e-95e4-f9258fc7888d</RoleDatumUuid>
        <RoleDatumUuid>1b22babd-016f-4030-aeff-c5fc76ca79ea</RoleDatumUuid>
        <RoleDatumUuid>f9cf8fd3-c720-46e3-8c9c-05db58ff896a</RoleDatumUuid>
        <RoleDatumUuid>07b6efc3-0e34-4b1c-8026-5d718c79e76e</RoleDatumUuid>
        <RoleDatumUuid>807c1273-71a0-4ebb-9af3-16de36b7ec5a</RoleDatumUuid>
        <RoleDatumUuid>9fed9090-38fd-4992-852e-f6112b0d490e</RoleDatumUuid>
        <RoleDatumUuid>7d18cd7c-11be-41b1-aa4c-51fee4e25417</RoleDatumUuid>
        <RoleDatumUuid>cfbf5f95-a843-421b-9c8b-5032d448b5f6</RoleDatumUuid>
        <RoleDatumUuid>39e6d770-f5af-4396-ac8e-9e7ea174e8b0</RoleDatumUuid>
        <RoleDatumUuid>b4355e44-dc99-4876-9eb6-e1b274d0a85b</RoleDatumUuid>
        <RoleDatumUuid>610947b2-1eb9-4aa4-a147-1c8eefd2459e</RoleDatumUuid>
        <RoleDatumUuid>ab9ff9bf-3da9-4800-a790-98b2c62c033c</RoleDatumUuid>
      </RoleGroup>
    </RoleGroupList>
    <RoleGroupList RoleTypeName="SafetyVariable" />
  </DataList>
</DataListDocument>